#!/bin/bash

APP="$1"; IMAGE="$2"
echo "-----> Building Node app ..."
COMMAND=$(cat <<EOF
cd "\$DOKKU_ROOT/\$APP" &&
server/prepare_dist &&
npm update &&
bower install &&
bower update &&
grunt build
EOF
)

id=$(docker run -d $IMAGE /bin/bash -c "$COMMAND")
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
echo "-----> Built Node"
